#!/usr/bin/env python3
"""Writes shared/test-vectors/sanitise_fuzz.json (docs/design.md §12 Phase 4).

A seeded corpus of hostile strings built from escape fragments, UTF-8 edge
cases and invalid bytes. The expected results come from the Python sanitiser
(shared/python/corkcore); the Lua suite must give the same answer for every
case, which is the "rejected identically in Lua and Python" check.

    python3 shared/test-vectors/tools/gen_sanitise_fuzz.py
"""

import json
import random
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / "shared" / "python"))

from corkcore import sanitise  # noqa: E402

SEED = 20260926
CASES = 600

FRAGMENTS = [
    b"|", b"||", b"|c", b"|cff00ff00", b"|cFFFFFFF", b"|cffggffgg", b"|cnIQ4:", b"|cn:", b"|cnBAD", b"|r", b"|H",
    b"|Hitem:1|h[x]|h", b"|Hitem:1|h[x]", b"|Hbogus:1|h[x]|h", b"|Hitem:|h|h", b"|Hquest:7:5|h[Kobold]|h",
    b"|Hspell:133|h", b"|Hachievement:6|h[a|h", b"|T", b"|TInterface\\Icons\\x:0|t", b"|A", b"|K", b"|n", b"|h",
    b"a", b"Z", b"0", b" ", b"-", b":", b"[", b"]", b"h", b"\n", "é".encode(), "日".encode(), "😀".encode(),
    " ".encode(),
]
# Rarer: each case gets at most one of each, so every reason is well covered.
CONTROLS = [b"\t", b"\r", b"\x00", b"\x1f", b"\x7f"]
INVALID = [b"\xff", b"\xc0\xaf", b"\xed\xa0\x80", b"\xf4\x90\x80\x80", b"\xe2\x82", b"\x80"]


def build(rng):
    parts = [rng.choice(FRAGMENTS) for _ in range(rng.randint(0, 24))]
    for extra, chance in ((CONTROLS, 0.12), (INVALID, 0.12)):
        if rng.random() < chance:
            parts.insert(rng.randint(0, len(parts)), rng.choice(extra))
    data = b"".join(parts)
    if rng.random() < 0.05:
        data = data * rng.randint(40, 200)
    return data


def main():
    rng = random.Random(SEED)
    text, names, boards = [], [], []
    seen = set()
    while len(text) < CASES:
        data = build(rng)
        if data in seen:
            continue
        seen.add(data)
        value = data.decode("utf-8", "surrogateescape")
        ok, reason = sanitise.text(value)
        case = {"input_hex": data.hex(), "ok": ok}
        if not ok:
            case["reason"] = reason
        text.append(case)
        if len(data) < 80:
            names.append({"input_hex": data.hex(), "ok": sanitise.name(value)})
            boards.append({"input_hex": data.hex(), "ok": sanitise.board_name(value)})
    out = {
        "seed": SEED,
        "note": "Generated by tools/gen_sanitise_fuzz.py from the Python sanitiser. Don't edit by hand.",
        "text": text,
        "name": names,
        "board_name": boards,
    }
    path = ROOT / "shared" / "test-vectors" / "sanitise_fuzz.json"
    path.write_text(json.dumps(out, indent=1) + "\n", encoding="utf-8")
    counts = {}
    for case in text:
        key = case.get("reason", "ok")
        counts[key] = counts.get(key, 0) + 1
    print(f"{len(text)} text cases, {len(names)} name cases:", dict(sorted(counts.items())))


if __name__ == "__main__":
    main()
